apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: echo-message
      taskRef:
        name: echo-task
      params: 
        - name: message
          value: $(params.message)
  
# This is a simple pipeline with hello world task.
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-pipeline
spec:
  params:
    - name: url
    - name: branch
  tasks:
    - name: git-clone-task
      taskRef:
        name: git-clone-task
      params:
        - name: url
          value: $(params.url)
        - name: branch
          value: $(params.branch)