apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-workspace-content
spec:
  workspaces:
  - name: source
  steps:
  - name: list-files
    image: ubuntu
    script: |
      ls -la $(workspaces.source.path)
      # find $(workspaces.source.path) -type f -exec echo {} \; -exec cat {} \;