server:
  port: 8085

logging:
  level:
    springfox:
      documentation: DEBUG


cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true


