data-provider:
  polygon:
    baseUrl: https://api.polygon.io
    apiKey:
  vantage:
    baseUrl: https://api.vantage.trade
    apiKey: 

logging:
    level:
        org:
            springframework:  DEBUG
            flywaydb: DEBUG
            hibernate: DEBUG
            liquibase: DEBUG


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market_reference_data
    username: sa
    password: password
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/market_reference_data
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:postgresql://localhost:5432/market_reference_data
    user: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true




server:
  port: 8089